// import { truck } from '@/assets';
import truck from "@/assets/images/truck.png";
import check from "@/assets/images/check.png";
import feature from "@/assets/images/feature.png";
import card from "@/assets/images/card.png";
import stul from "@/assets/images/stul.png";
import stul2 from "@/assets/images/Photo.png";
import stul3 from "@/assets/images/img2.png";
import stul4 from "@/assets/images/img3.png";
import imag1 from "@/assets/images/Large.png";
import imag2 from "@/assets/images/img4.png";
export { truck, feature, card, check, stul, stul2, stul3, stul4, imag1, imag2 };
